### ISSUE TITLE
handle non-commands

### ISSUE THREAD

**Issue by bytesuji** [LawOfExcludedMiddle/todo#4]
i.e., for `ls` it should print `reeee not a command` and continue. when I type `-1` it just doesn't do anything.

**Comment by LawOfExcludedMiddle** [comment]
REEEEEEEEEEEEEEsolved

**Comment by bytesuji** [comment]
this still doesn't work for me

```
TODO:
-----
lance> baka
#>
```

Worked once and then stopped working. Haven't changed anything. Even when it worked, I only saw the message once, and typing in another non-command would crash it.
